Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10
}
Config.Linux = true      -- True if linux
Config.TweetDuration = 24 -- How many hours to load tweets (12 will load the past 12 hours of tweets)
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 'M'
Config.PhoneApplications = {
    ['phone'] = {
        app = 'phone',
        color = '#04b543',
        icon = 'fa fa-phone-alt',
        tooltipText = 'Telefone',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
	['whatsapp'] = {
        app = 'whatsapp',
        color = '#25d366',
        icon = 'fas fa-comment',
        tooltipText = 'Whatsapp',
        tooltipPos = 'top',
        style = 'font-size: 2.8vh',
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
		password = true,
        creator = 'QBCore',
        title = 'Whatsapp',
	},
    ['settings'] = {
        app = 'settings',
        color = '#636e72',
        icon = 'fa fa-cogs',
        tooltipText = 'Configurações',
        tooltipPos = 'top',
        style = 'padding-right: .08vh; font-size: 2.3vh',
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ['twitter'] = {
        app = 'twitter',
        color = '#1da1f2',
        icon = 'fab fa-twitter',
        tooltipText = 'Twitter',
        tooltipPos = 'top',
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ['garage'] = {
        app = 'garage',
        color = '#575fcf',
        icon = 'fas fa-car',
        tooltipText = 'Veiculos',
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ['mail'] = {
        app = 'mail',
        color = '#ff002f',
        icon = 'fas fa-envelope-open-text',
        tooltipText = 'E-mail',
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ['advert'] = {
        app = 'advert',
        color = '#ff8f1a',
        icon = 'fas fa-bullhorn',
        tooltipText = 'Classificados',
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ['bank'] = {
        app = 'bank',
        color = '#9c88ff',
        icon = 'fas fa-money-check-alt',
        tooltipText = 'Banco',
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ['crypto'] = {
        app = 'crypto',
        color = '#004682',
        icon = 'fas fa-coins',
        tooltipText = 'Cryptomoedas',
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ['racing'] = {
        app = 'racing',
        color = '#353b48',
        icon = 'fas fa-flag-checkered',
        tooltipText = 'Corridas',
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ['houses'] = {
        app = 'houses',
        color = '#27ae60',
        icon = 'fas fa-home',
        tooltipText = 'Casas',
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ['lawyers'] = {
        app = 'lawyers',
        color = '#26d4ce',
        icon = 'fas fa-briefcase',
        tooltipText = 'Serviços',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ['gallery'] = {
        app = 'gallery',
        color = '#AC1D2C',
        icon = 'fas fa-images',
        tooltipText = 'Galeria',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ['camera'] = {
        app = 'camera',
        color = '#AC1D2C',
        icon = 'fas fa-camera',
        tooltipText = 'Camera',
        tooltipPos = 'bottom',
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ['meos'] = {
        app = 'meos',
        color = '#004682',
        icon = 'fas fa-ad',
        tooltipText = 'MDT',
        job = 'police',
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
	['trucker'] = {
        app = 'trucker',
        color = '#353b48',
        icon = 'fas fa-globe-europe',
        tooltipText = 'Entregador',
        tooltipPos = 'right',
        job = 'trucker',
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
}
Config.MaxSlots = 20

Config.StoreApps = {
    ['territory'] = {
        app = 'territory',
        color = '#353b48',
        icon = 'fas fa-globe-europe',
        tooltipText = 'Territory',
        tooltipPos = 'right',
        style = '',
        job = false,
        blockedjobs = {},
        slot = 18,
        Alerts = 0,
        password = true,
        creator = 'QBCore',
        title = 'Territory',
    },
}
